version: '3'
services:
  todotests:
    image: todotests
    depends_on:
      - todofrontend
    environment:
      - FRONT_HOST=todofrontend

  todofrontend:
    image: todofrontend
    depends_on:
      - todobackend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=todobackend

  todobackend:
    image: todobackend
    ports:
      - 3001:3001

